site_name: Еда для татар и не только!
site_url: https://go9ol.github.io/mkdocs-demo1/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
