site_name: Aidar is testing vs code with Mkdocs
site_url: https://go9ol.github.io/mkdocs-demo1/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
